// This file is generated by the rs-update-tests script

#include "rs-unit-test.hpp"

int main(int argc, char** argv) {

    RS::UnitTest::begin_tests(argc, argv);

    // version-test.cpp
    UNIT_TEST(options_version)

    // options-traits-test.cpp
    UNIT_TEST(rs_options_traits)

    // options-help-test.cpp
    UNIT_TEST(rs_options_help)

    // options-parsing-test.cpp
    UNIT_TEST(rs_options_parsing)

    // options-required-test.cpp
    UNIT_TEST(rs_options_required)

    // options-boolean-test.cpp
    UNIT_TEST(rs_options_boolean)

    // options-anonymous-test.cpp
    UNIT_TEST(rs_options_anonymous)

    // options-container-test.cpp
    UNIT_TEST(rs_options_container)

    // options-pattern-match-test.cpp
    UNIT_TEST(rs_options_pattern_match)

    // options-enumeration-test.cpp
    UNIT_TEST(rs_options_enumeration)

    // options-mutual-exclusion-test.cpp
    UNIT_TEST(rs_options_mutual_exclusion)

    // unit-test.cpp

    return RS::UnitTest::end_tests();

}
